# Generated by Django 5.1.4 on 2025-01-08 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_product_name_payment_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='user_name',
            new_name='user',
        ),
    ]
